### ISSUE TITLE
Problem open Mirth Connect

### ISSUE THREAD

**Issue by LuisMirth** [kayyagari/git-ext#4]
Al intentar abrir mirth connect una vez añadida la extensión me aparece este error.
com.mirth.connect.client.launcher.q: java.lang.Exception: Error verifying entry "META-INF/MANIFEST.MF" in JAR file git-ext-client-1.0.1-SNAPSHOT.jar
java.util.concurrent.ExecutionException: com.mirth.connect.client.launcher.q: java.lang.Exception: Error verifying entry "META-INF/MANIFEST.MF" in JAR file git-ext-client-1.0.1-SNAPSHOT.jar
at java.util.concurrent.FutureTask.report(Unknown Source)
at java.util.concurrent.FutureTask.get(Unknown Source)
at com.mirth.connect.client.launcher.f.a(SourceFile:415)
at com.mirth.connect.client.launcher.f.a(SourceFile:370)
at com.mirth.connect.client.launcher.MirthClientLauncher.run(SourceFile:1230)
at java.lang.Thread.run(Unknown Source)
Caused by: com.mirth.connect.client.launcher.q: java.lang.Exception: Error verifying entry "META-INF/MANIFEST.MF" in JAR file git-ext-client-1.0.1-SNAPSHOT.jar
at com.mirth.connect.client.launcher.r.a(SourceFile:262)
at com.mirth.connect.client.launcher.r.a(SourceFile:200)
at com.mirth.connect.client.launcher.f.a(SourceFile:549)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
... 1 more
Caused by: java.lang.Exception: Error verifying entry "META-INF/MANIFEST.MF" in JAR file git-ext-client-1.0.1-SNAPSHOT.jar
at com.mirth.connect.client.launcher.r.a(SourceFile:249)
... 6 more
Caused by: java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.
at org.bouncycastle.jce.provider.PKIXCertPathValidatorSpi.engineValidate(Unknown Source)
at java.security.cert.CertPathValidator.validate(Unknown Source)
at com.mirth.connect.client.launcher.r.a(SourceFile:347)
at com.mirth.connect.client.launcher.r.a(SourceFile:241)
... 6 more

**Comment by jonbartels** [comment]
Make sure you are using the latest version of the Launcher.

Run the launcher with `-k -d`

```
java -jar mirth-client-launcher.jar --help
INFO  2022-02-17 08:54:15,711 [main] com.mirth.connect.client.launcher.MirthClientLauncher: Arguments: [--help]
usage: launch
 -a,--address <arg>            The address to connect to Mirth Connect
                               with.
 -d,--allow-incorrect-digest   Allows JARs that fail digest verification.
                               This should only be used for
                               development/testing purposes.
 -h,--help                     Prints this help message.
 -j,--java-console             If specified, the Administrator will be
                               launched with a Java console dialog.
 -k,--allow-self-signed        Allows JARs signed with self-signed
                               certificates to be verified. This should
                               only be used for development/testing
                               purposes.
 -m,--max-heap-size <arg>      The client-side max heap size to use when
                               launching the Administrator.
 -o,--stay-open                If specified, the launcher will stay open
                               after launching the Administrator.
 -v,--use-same-jvm             If specified, the Administrator will be
                               launched using the same JVM as the
                               launcher. Useful when you don't have access
                               to a launcher script.
```

**Comment by LuisMirth** [comment]
I am using version 3.12 of the launcher.

**Comment by jonbartels** [comment]
From https://github.com/kpalang/mirth-plugin-guide

> If you start you Launcher like you usually do, though the shortcut the installation created, you're not going to be able to log in to Mirth. This is because our plugin is signed using a self-signed certificate and this is something Mirth Administrator Launcher explicitly distrusts in a production environment.
To get around this limitation, we're going to have to start our launcher with a -k flag. To do that follow these steps:

The author shows how to set this for MacOS and Windows.

**Comment by LuisMirth** [comment]
Perfect!! Thank you!!

**Comment by LuisMirth** [comment]
Hi,
Thanks for your help. I already see the version History tab, but in the settings the connection with GIT does not appear.
